name: building, linting, testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v2
      - name: setting up nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: installing node_modules
        run: npm install
      - name: build production version of the project
        run: npm run build:prod
      - name: linting for typescript
        run: npm run lint:ts
      - name: linting for styles
        run: npm run lint:scss
      - name: run unit tests
        run: npm run tests:unit